# Generated by Django 5.1.4 on 2026-04-22 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('capacidad_asientos', models.PositiveIntegerField(default=10)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licencia_numero', models.CharField(max_length=50, unique=True)),
                ('licencia_categoria', models.CharField(blank=True, default='', max_length=20)),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conductor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductores',
                'ordering': ['usuario__nombres'],
            },
        ),
    ]
