# Generated by Django 5.1.4 on 2026-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
