# Generated by Django 5.1.4 on 2026-04-22 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Paradero',
                'verbose_name_plural': 'Paraderos',
                'db_table': 'paraderos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('origen_nombre', models.CharField(max_length=120)),
                ('destino_nombre', models.CharField(max_length=120)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_estimada_min', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaParadero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('ORIGEN', 'Origen'), ('INTERMEDIO', 'Intermedio'), ('DESTINO', 'Destino')], max_length=20)),
                ('tiempo_estimado_min', models.IntegerField(blank=True, null=True)),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_rel', to='routes.paradero')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraderos_rel', to='routes.ruta')),
            ],
            options={
                'verbose_name': 'Paradero en ruta',
                'verbose_name_plural': 'Paraderos por ruta',
                'db_table': 'ruta_paraderos',
                'ordering': ['ruta', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('ruta', 'orden'), name='uq_ruta_orden'), models.UniqueConstraint(fields=('ruta', 'paradero'), name='uq_ruta_paradero')],
            },
        ),
        migrations.CreateModel(
            name='TarifaTramo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('paradero_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_como_destino', to='routes.paradero')),
                ('paradero_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_como_origen', to='routes.paradero')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='routes.ruta')),
            ],
            options={
                'verbose_name': 'Tarifa por tramo',
                'verbose_name_plural': 'Tarifas por tramo',
                'db_table': 'tarifas_tramo',
                'ordering': ['ruta', 'paradero_origen', 'paradero_destino'],
                'constraints': [models.UniqueConstraint(fields=('ruta', 'paradero_origen', 'paradero_destino'), name='uq_tarifa_ruta_tramo')],
            },
        ),
    ]
