# Generated by Django 5.1.4 on 2026-04-23 00:13

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='trips.viaje')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'asientos',
                'ordering': ['viaje', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(default=apps.tickets.models.default_expira_en)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('paradero_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_destino', to='routes.paradero')),
                ('paradero_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_origen', to='routes.paradero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='trips.viaje')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_token', models.CharField(default=apps.tickets.models.generate_qr_token, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('USADO', 'Usado (abordado)'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('asiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boleto', to='tickets.asiento')),
                ('paradero_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_destino', to='routes.paradero')),
                ('paradero_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_origen', to='routes.paradero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='trips.viaje')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='tickets.reserva')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'db_table': 'boletos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ReservaAsiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_reserva', to='tickets.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.reserva')),
            ],
            options={
                'db_table': 'reserva_asientos',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.ManyToManyField(related_name='reservas', through='tickets.ReservaAsiento', to='tickets.asiento'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('viaje', 'numero'), name='uq_asiento_viaje_numero'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['usuario', 'estado'], name='idx_boleto_usuario_estado'),
        ),
        migrations.AddConstraint(
            model_name='reservaasiento',
            constraint=models.UniqueConstraint(fields=('reserva', 'asiento'), name='uq_reserva_asiento'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario', 'estado'], name='idx_reserva_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['viaje', 'estado'], name='idx_reserva_viaje_estado'),
        ),
    ]
