# Generated by Django 5.1.4 on 2026-04-22 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('dias_semana', models.CharField(blank=True, default='', help_text='Códigos separados por coma: L,M,X,J,V,S,D', max_length=20)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='routes.ruta')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
                'ordering': ['ruta', 'hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateField()),
                ('hora_salida_programada', models.DateTimeField()),
                ('hora_salida_real', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('capacidad_total', models.PositiveIntegerField()),
                ('asientos_disponibles', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='fleet.conductor')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='trips.horario')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='routes.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='fleet.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viajes',
                'ordering': ['-fecha_viaje', 'hora_salida_programada'],
                'indexes': [models.Index(fields=['fecha_viaje', 'estado'], name='idx_viajes_fecha_estado')],
            },
        ),
    ]
