# Generated by Django 5.1.4 on 2026-04-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='min_pasajeros_para_salir',
            field=models.PositiveIntegerField(default=0, help_text='Umbral para avisar al conductor que puede salir. 0 = sin mínimo.'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_abiertos', to='routes.paradero'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto (tomando pasajeros)'), ('PROGRAMADO', 'Programado (legacy)'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20),
        ),
    ]
